services:
  clock_app:
    build: ./clock_app
    ports:
      - "5001:5001"
    networks:
      - clock_network

  button_app:
    build: ./button_app
    ports:
      - "5002:5002"
    networks:
      - clock_network

networks:
  clock_network:
    driver: bridge





