version: '3.8'

services:
  web:
    build: .
    ports:
      - "6000:5000"
  sqldb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"